#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:base64", "base64")

apiVersion: v1
kind: Secret
metadata:
  name: concourse-vault
  namespace: concourse
type: Opaque
data:
  vault-client-auth-param: #@ base64.encode(data.values.concourse.vault.auth_param)

#@overlay/match by=overlay.subset({"kind":"Deployment","metadata":{"name":"concourse-web"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by="name"
      - name: concourse-web
        env:
        #@overlay/match by="name"
        - name: CONCOURSE_KUBERNETES_IN_CLUSTER
          value: "false"
        #@overlay/match by="name", missing_ok=True
        - name: CONCOURSE_VAULT_URL
          value: #@ data.values.concourse.vault.url
        #@overlay/match by="name", missing_ok=True
        - name: CONCOURSE_VAULT_AUTH_BACKEND
          value: approle
        #@overlay/match by="name", missing_ok=True
        - name: CONCOURSE_VAULT_AUTH_PARAM
          valueFrom:
            secretKeyRef:
              name: concourse-vault
              key: vault-client-auth-param