#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:overlay", "overlay")

apiVersion: v1
kind: Secret
metadata:
  name: concourse-web-tls
  namespace: concourse
type: kubernetes.io/tls
data:
  tls.crt: #@ base64.encode(data.values.secrets.web_tls_cert)
  tls.key: #@ base64.encode(data.values.secrets.web_tls_key)