#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")

apiVersion: v1
kind: Namespace
metadata:
  name: concourse

#@overlay/match by=overlay.not_op(overlay.subset({"kind": "Namespace"})), expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  namespace: concourse

#@ concourse = library.get("concourse")
--- #@ template.replace(concourse.eval())